- app/models/instance/as_typeahead/for_synonymy.rb
- app/views/instances/_form_create_synonymy.html.erb
- config/history/changes-2024.yml
- config/version.properties
- test/fixtures/authors.yml
- test/fixtures/instances.yml
- test/fixtures/names.yml
- test/fixtures/references.yml
- test/models/instance/as_typeahead/for_synonymy/phrase_name_with_digit_search.rb
- test/models/instance/as_typeahead/for_synonymy/test_helper.rb
- test/models/search/on_instance/name_status_not/simple_test.rb
NSL-2820: Synonymy typeahead: Treat 4 consecutive digits as a year for searching, rather than just any sequence of digits; improve placeholder text
> NSL-2820: Synonymy typeahead: Treat 4 consecutive digits as a year for searching

- app/controllers/services_controller.rb
- config/history/changes-2024.yml
- config/routes.rb
- config/version.properties
- test/controllers/services_controller_test.rb
Ping, build, and other services will still be available.
> NSL-4483:  Services: Remove unnecessary services index page which listed the ping service. 

- app/models/concerns/loader/name/sourced_synonyms.rb
- app/views/loader/names/tabs/_tab_matched_name.html.erb
- config/history/changes-2024.yml
- config/version.properties
This is when copying synonyms from a standalone instance with synonyms into a loader batch.
> NSL-4847:  Loader: Correct instance now being carried across when synonyms are copied into the loader

- app/controllers/instances_controller.rb
- config/history/changes-2024.yml
- config/version.properties
Limit the display of Instance Loader tab in a way similar to the Copy tab, but extended to synonyms.
> NSL-4944: Loader: Allow copy of concepts to a loader batch from target instances only

- app/models/concerns/loader/name/preferred_match.rb
- config/history/changes-2024.yml
- config/version.properties
> NSL-4941: Loader: When copying synonymy include existing matches for misapplications

- app/models/search/loader/name/field_rule.rb
- app/models/search/on_model/predicate.rb
- app/views/loader/names/help/_fields.html.erb
- config/history/changes-2024.yml
- config/version.properties
Added this to the on_model search code, which is the latest version of the search engine.
> NSL-4945:  Loader: Searches on any-batch: with an argument will give an error message; field help now also explains it takes no argument

- app/models/search/loader/name/field_rule.rb
- config/history/changes-2024.yml
- config/version.properties
If syn-match-in-tree directive is submitted without an argument the user gets a general message urging them to review their search directives and arguments.
> NSL-5017:  Loader: Require an argument for search directive syn-match-in-tree

- app/models/loader/name/make_one_match.rb
- config/history/changes-2024.yml
- config/version.properties
Three decline tests were bundled into one decline path, so separate these decline tests into separate steps.
Also minor refactoring by adding a single decline method that takes the reason as an argument.
Retain the correct process for allowing the job to collect numbers declined and reasons declined.
> NSL-4979: Loader: Improve accuracy of decline reasons for job that creates preferred matches

- app/views/loader/names/tabs/forms/_form_for_accepted_or_excluded.html.erb
- app/views/loader/names/tabs/forms/_form_for_heading.html.erb
- app/views/loader/names/tabs/forms/_form_for_misapp.html.erb
- app/views/loader/names/tabs/forms/_form_for_synonym.html.erb
- app/views/loader/names/tabs/forms/_simple_name_full_name.html.erb
- config/history/changes-2024.yml
- config/version.properties
Changes apply to forms for 
- accepted/excluded names
- synonyms
- misapplieds
- headings (just in case)
Extracted code for simple and full names into a partial to make this cleaner.
> NSL-4997: Loader: Prevent edits to simple or full name when a preferred match has been set

- app/controllers/name/matches/typeaheads/for_unpub_cit_controller.rb
- config/version.properties
…/name/matches/typeaheads/for_unpub_cit_controller.rb
> Fix definition of class to match file path for editor/app/controllers/name/matches/typeaheads/for_unpub_cit_controller.rb

- app/controllers/loader/batch/bulk_controller/remove_syn_conflicts_job.rb
- app/models/concerns/loader/name/partials.rb
- app/models/loader/name.rb
- app/models/loader/name/bulk_syn_conflicts_search.rb
- app/models/loader/name/match.rb
- app/models/search/loader/name/field_rule.rb
- app/views/loader/names/tabs/details/matches/synonyms/forms/preferred_matches/_one_match.html.erb
- config/history/changes-2024.yml
- config/version.properties
Required changes to:
* syn-match-in-tree report sql
* syn-match-in-tree family sql
* loader name details tab warning code
* search for bulk job to remove syn conflicts
> NSL-5013:  Loader: Stop flagging synonyms as clashing with names in taxonomy if the synonym loader_name_match record has a partial relationship type

- app/controllers/loader/names_controller.rb
- app/javascript/fresh.js
- app/views/loader/names/new.html.erb
- app/views/loader/names/new.js.erb
- app/views/loader/names/new_row_here.js.erb
- config/history/changes-2024.yml
- config/version.properties
Wrangled some of the JS involved in shifting focus, handling keyboard navigation, and showing current record in the details area.
Also did some clean up:
- Moved function addRow from view code to addNewRow in fresh.js.
- Removed uncalled function nedLoadDetails
> NSL-5044: Loader: Clicking plus sign to add new entry no longer breaks arrow navigation

- app/models/concerns/loader/name/sort_key.rb
- app/views/loader/names/tabs/forms/_sort_key_or_seq.html.erb
- config/history/changes-2024.yml
- config/version.properties
In general, when you save changes to a `loader_name` record the `sort_key` will be reset.  That general rule has some exceptions and details to understand.
1. If the batch is sequence-ordered the `sort_key` will be emptied.
1. For `sort_key` ordered batches:
1. if `sort_key` is empty it will be set to a calculated/default value
1. if `sort_key` has a value and the `record_type` is one of the following it will not be reset:
- heading
- in-batch-note
- in-batch-compiler-note
1. if `sort_key` has a value and the `sort_key` was NOT also changed in the submitted data, the value will  be reset
-  we assume a change to `sort_key` value is someone setting a custom value, that’s why we don’t reset it in this case
> NSL-5086: Loader: Refresh sort key values when loader records are edited

- app/controllers/loader/batch/bulk_controller/add_to_draft_taxonomy_job.rb
- app/controllers/loader/batch/bulk_controller/create_draft_instance_job.rb
- app/controllers/loader/batch/bulk_controller/create_preferred_matches_job.rb
- app/controllers/loader/batch/bulk_controller/remove_syn_conflicts_job.rb
- config/history/changes-2024.yml
- config/version.properties
Added elapsed time for these jobs:
- create preferred matches
- create draft instances
- remove syn conflicts
- add to draft taxonomy
The elapsed time is shown:
- as seconds if less than 60 seconds
- as seconds and as minutes/seconds if more than 60 seconds
I also added some extra useful information:
- job title
- job batch
- job search specification
> NSL-5099:  Loader: Added elapsed time to the job summary reports.

- app/controllers/names_controller.rb
- app/javascript/fresh.js
- app/models/name/as_new.rb
- app/views/authors/_new_row.html.erb
- app/views/layouts/_new_menu.html.erb
- app/views/names/_new.html.erb
- app/views/names/_new_row.html.erb
- app/views/names/new.html.erb
- app/views/names/new.js.erb
- app/views/names/new_row.js.erb
- config/history/changes-2024.yml
- config/routes.rb
- config/version.properties
- test/controllers/names/new/scientific_family_or_above/simple_test.rb
- test/controllers/names/new_row/cultivar/simple_test.rb
- test/controllers/names/new_row/cultivar_hybrid/simple_test.rb
- test/controllers/names/new_row/hybrid_formula/simple_test.rb
- test/controllers/names/new_row/hybrid_formula_unknown_2nd_parent/simple_test.rb
- test/controllers/names/new_row/other/simple_test.rb
- test/controllers/names/new_row/phrase_name/simple_test.rb
- test/controllers/names/new_row/scientific/simple_test.rb
- test/controllers/names/routes/new_test.rb
Covers the 8 types of Name records
- Arrow up/down navigation now working for the 8 types of new name records.
Extra changes
While working on the code for inserting new name records I noticed several trivial but annoying inconsistencies, so I tidied them up while there. 
- Standardised the title case of the names on the LHS records to match the title on the RHS tab for each type of name.
Extras for “Scientific Name Family and Above”:
- Changed the New menu entry from Scientific name family and above   to Scientific name family or above (and to or)
- Changed the LHS record title from: New scientific_family name to New Scientific Name - Family or Above
- Added a sub-heading on the RHS data entry form: Family or Above
> NSL-5104:  Editor: Make it possible to arrow in and out of new records created from the New menu

- app/models/concerns/loader/name/doubt.rb
- app/models/loader/name.rb
- app/views/loader/names/help/_fields.html.erb
- config/history/changes-2024.yml
- config/version.properties
Background
In Feb I added a doubtful? method that gave precedence to loader_name.synonym_type - if that field existed, the code ignored loader_name.doubtful field.
This was designed for print output - displaying question marks.
Unfortunately it had a side-effect on the process for determining relationship type in preferred matches - result was that doubt was not taken into account for synonyms.
Change
I’ve now split the code so the side-effect will not happen.  Relationship type should now take account of doubt.
Extra
Also fixed incidental typo in loader name search help
> NSL-5113:  Loader: Match relationship type will take account of doubt

- Gemfile
- Gemfile.lock
- app/controllers/names_controller.rb
- app/jobs/name_children_refresher_job.rb
- app/models/concerns/name_namable.rb
- app/models/concerns/name_name_pathable.rb
- app/models/concerns/name_validatable.rb
- config/history/changes-2024.yml
- config/version.properties
- test/controllers/names/edit/genus_name_update_with_no_name_change_test.rb
- test/models/name/create/author_and_ex_author_must_differ_test.rb
- test/models/name/create/base_author_and_ex_base_author_must_differ_test.rb
- test/test_helper.rb
I changed the algorithm so that children (and grandchildren, etc) are refreshed if either the simple_name or full_name of a name is altered (taking into account they are generated by calls to a service).
There will also be a message on screen to indicate such a downstream update has occurred.  
I also removed some unused testing gems while reviewing tests for this change.
> NSL-2494: Ensure Name children/descendents' constructed fields are refreshed in more cases

- app/controllers/names_controller.rb
- app/models/concerns/name_name_pathable.rb
- config/history/changes-2024.yml
- config/version.properties
Also prevent unrelated validation errors interrupting a refresh.
There was a rare case of records with null name_element exploiting a weakness in the name_path construction code leading to null name_path.
The code now properly returns a non-null name_path even for records with a null name_element.
> NSL-5118:  Name Path Refresh: Prevent blank name_path being generated during refresh.

- app/models/loader/name/match/as_typeahead/for_intended_tree_parent_instance.rb
- config/history/changes-2024.yml
- config/version.properties
Common names are no longer offered
> NSL-5120: Loader: Typeahead for Taxonomy Parent on the Matched Name tab now offers scientific names only

- app/views/loader/names/_new_row.html.erb
- app/views/loader/names/create.js.erb
- app/views/loader/names/create_heading.js.erb
- app/views/loader/names/new_row_here.js.erb
- config/history/changes-2024.yml
- config/version.properties
i.e. when cursor is placed in the new Loader Name record to start with, up/down key nav works as expected
> NSL-5121:  New Record navigation: Extend fix to new Loader Name records

- app/javascript/fresh.js
- app/views/loader/names/tabs/_tab_create_misapp.html.erb
- app/views/loader/names/tabs/_tab_create_syn.html.erb
- app/views/loader/names/tabs/forms/_form_for_accepted_or_excluded.html.erb
- app/views/loader/names/tabs/forms/_form_for_synonym.html.erb
- app/views/loader/names/tabs/forms/_simple_name_full_name.html.erb
- app/views/loader/names/tabs/forms/_sort_key_or_seq.html.erb
- config/history/changes-2024.yml
- config/version.properties
Also set focus on full name for synonym/misapp record forms
> NSL-5114: Loader: Move record type near top of accepted/excluded record form

- app/javascript/fresh.js
- config/history/changes-2024.yml
- config/version.properties
Refine the way JS code sets focus inside a RHS tab.
> NSL-5139: Reviewer tab click: Stop rogue navigation to another record

- app/controllers/name_tag_names_controller.rb
- config/history/changes-2024.yml
- config/version.properties
Was due to Rails 7.1 detecting a minor code discrepancy:
`The update action could not be found for the :set_name_tag_name
callback on NameTagNamesController, but it is listed in the controller's
:only option.`
Simply removed the update action from the callback.
> NSL-5148: Rails Upgrade: Fix tag insert for names 

- app/views/application/search_results/review/_loader_name_record.html.erb
- config/history/changes-2024.yml
- config/version.properties
First name of a result set if it was excluded wouldn't show comment or distribution.
> NSL-5175: Loader: Display taxonomy comment for reviewer where it wasn't showing up.

- app/views/instances/tabs/batch_loader/_form_to_supplement_concept.html.erb
- config/history/changes-2024.yml
- config/version.properties
The batch drop down was not being honoured by the typeahead dropdown because that typeahead is set up when the form is loaded and therefore doesn't know what batch the user could have chosen when the form is running.
This made the batch dropdown misleading and unhelpful.
I chose to simply remove the batch dropdown and not go down the path of setting up JS code to reset the typeahead
any time a user changes the batch selection in the form.  To take the more complex approach would be a departure from the
KISS approach to forms in the Editor.  There are so many forms and the goal is to keep them generally maintainable by keeping them simple.
Also, it is very easy (two clicks) to reset the default batch from the menu.  I think that's a very easy alternative.
The users rep has allowed this …
> NSL-5180:  Loader: Remove the batch drop down from Loader 2 tab

- config/version.properties
- test/controllers/names/create/by_editor_test.rb
- test/controllers/names_deletes/confirm/for_editor/simple_test.rb
- test/controllers/references/create/simple_test.rb
- test/controllers/references/edit/iso_publication_date/partial_date/month_and_year_test.rb
- test/controllers/workspace/placement/create_test.rb
- test/controllers/workspace/placement/remove_test.rb
The external requests in docker have different user-agent (rest-client/2.1.0 (linux aarch64) ruby/3.3.3p89) which causes the tests to fail as it has not been stubbed in the codes.
Updated the stubbed requests in the controller tests by removing the user-agent header.
> Update stubbed requests in controller tests

- README.md
- config/version.properties
- db/structure.sql
- test/fixtures/trees.yml
I generated a new `structure.sql` file using the recently modified rails rake task - described in `README.md`.
I modified the `structure.sql` contents as described in `README.md`.
I added an rdf column value in the `trees` fixture file because this column is now `not null`.
I then ran all regression tests successfully against this updated database schema - but without activating the `foa_profile_aware` feature flag.
> Pick up latest database schema changes including FOA Profile tables

- app/views/application/search_results/review/_loader_name_record.html.erb
- config/history/changes-2024.yml
- config/version.properties
Also show when a family entry is merely a heading in query results by wrapping it in square brackets and making it non-clickable.
> NSL-5216: Loader Review: Allow for comments on family records

- config/version.properties
- test/models/profile/profile_item/defined_query/product_and_productt_item_configs_test.rb
Minitest is deprecating the assert_equal for nil assertions
> Use assert_nil in tests

- config/version.properties
- db/structure.sql
- test/fixtures/batch/review.yml
- test/fixtures/batch/review_period.yml
- test/fixtures/batch/review_role.yml
- test/fixtures/batch/reviewer.yml
- test/fixtures/org.yml
- test/fixtures/users.yml
- test/test_helper.rb
Added fixture files for:
* Batch_Review
* Batch_Review_Period
* Batch_Review_Role
* Batch_Reviewer
* Org
* Users
Also changed:
* structure.db - removed the `not null` constraint on several foreign key cols to allow fixtures to load. Not ideal, but better than trying to order the loading of all (?) fixtures.
* test_helper - re-instated `fixtures :all` because not sure why it was commented out
> Added some fixtures for loader batch tables.

- app/models/search/parsed_request.rb
- config/history/changes-2024.yml
- config/version.properties
- test/models/search/loader/name/print/fail_on_duplicate_print_directive.rb
- test/models/search/loader/name/print/fail_on_print_directive_with_arg.rb
- test/models/search/loader/name/print/simple_with_any_batch_test.rb
- test/models/search/loader/name/simple_with_batch_name_asterisk_test.rb
- test/models/search/on_name/with_print_directive_test.rb
Check for argument, which is unexpected.
Check for duplicates - to make checking for argument simpler.
Check only requested for targets that expect to print - currently only loader_name.
> NSL-5248: Validate the print directive

- app/assets/stylesheets/components/search-result-details.css
- app/views/profile_items/tabs/_tab_show_1.html.erb
- config/history/changes-2024.yml
- config/version.properties
From
To:
[x] Bump version 4.1.5.13
[x] Update changelog
> Change background color of link for markdown content

- app/controllers/profile_item_references_controller.rb
- config/history/changes-2025.yml
- config/version.properties
- test/controllers/profile_item_references_controller_test.rb
- Fixup the rescue block for the profile item reference create action that throws undefined method for :record when rescuing for a db-related error.
> Fixup the undefined record method in the rescue block

- app/models/concerns/instance_treeable.rb
- app/models/instance.rb
- app/models/tree_join_v.rb
- app/views/instances/_delete_widgets.html.erb
- app/views/instances/tabs/_tab_edit.html.erb
- app/views/instances/widgets/_no_delete_reasons.html.erb
- config/history/changes-2025.yml
- config/version.properties
This follows on from NSL-5242 which mistakenly broadened the refusal to delete if the instance is on any tree, not just if it's on a current tree.
That broadened refusal is not going to be rolled back because it accidentally and controversially  matches emerging requirements.
For this change, I have also removed in_taxo? from reasons to refuse delete because it is covered by the broader test in_any_tree?.
> NSL-5310:  Improve the screen explanation when you cannot delete an instance due to a tree entanglement

- app/models/instance_type.rb
- app/views/profile_item_references/_edit_form.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/instance_type_spec.rb
- test/models/instance_type/synonym_options_test.rb
For the Synonym instance_type dropdown, use the `relationship` column to query for the instance type options rather than the `citing` column
The affected pages/sections are:
- the instance type dropdown from the synonym tab
- the form for creating synonym instance
- the form for updating a synonym instance
- the dropdown in the loader
NSL-5323
> Use relationship boolean for the synonym option rather than citing

- app/models/instance_type.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/instance_type_spec.rb
- test/fixtures/instance_types.yml
- test/models/instance_type/synonym_options_test.rb
Update the unpub options query to also include `relationship=true`. This PR also includes updates on the fixtures
NSL-5323
> Update unpub query to use relationship=true

- app/models/loader/name/make_one_instance/make_one_synonymy_instance.rb
- config/history/changes-2025.yml
- config/version.properties
Tiny change to refer to a constant by its correct name.
Run loader with a specific case of an unpainted synonym (very rare) - Anna has a case ready from reporting this error.
> NSL-5341: Loader: Fix error handler to avoid uninitialized constant message for parenting error

- app/views/layouts/_user_menu.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/views/layouts/_user_menu_spec.rb
- test/factories/role_type.rb
We are putting back the codes for the user's product role list in the menu. Tests are also added back and should now be passing with CI
> Put back the codes for the product roles in the menu

- app/views/layouts/_user_menu.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/views/layouts/_user_menu_spec.rb
Update product role list in the menu to display the Product Name and Product Role Type (e.g APNI drafter) name. And also fixes the bug when hovering on the username - it was showing up a coded text rather than the actual username
Login -> hover on your name from the top menu -> hover on your username and you will see the list of the roles you are assigned to
FLOR-42
> Update product role list in the menu

- app/models/loader/batch/reviewer.rb
- app/models/org.rb
- config/history/changes-2025.yml
- config/version.properties
Missed some places the name column is referred to - found them and changed reference to user_name.
Run through batch voting workflow
> NSL-5331:  Loader: Recent column change in Users table from name to user_name cause problems in voting tab - fixed

- .github/workflows/test.yml
- config/history/changes-2025.yml
- config/version.properties
Update the  Github workflow so that tests will trigger when .erb files are changed
Open a PR with .erb file change
> Trigger gh ci when .erb files are updated

- app/controllers/concerns/search/query_defaults.rb
- config/history/changes-2025.yml
- config/version.properties
- test/controllers/search/loader/names/any_batch_test.rb
- test/controllers/search/loader/names/hardenbergia_any_batch_test.rb
- test/controllers/search/loader/names/hardenbergia_any_batch_with_limit_test.rb
- test/controllers/search/loader/names/hardenbergia_no_default_batch.rb
- test/controllers/search/loader/names/no_default_batch_test.rb
- test/controllers/search/loader/names/with_invalid_default_batch_and_limit_test.rb
- test/controllers/search/loader/names/with_invalid_default_batch_test.rb
Loader Name specific search bug fix - adjust regex for extracting default-batch declaration in search params.
Jira explains
> NSL-5340: Loader Name: Fix loss of limit directive when placed after default batch name

- app/models/ability.rb
- app/models/author.rb
- app/views/references/tabs/_tab_edit_3.html.erb
- app/views/references/tabs/_tabs.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/ability_spec.rb
- spec/models/author_spec.rb
Allow draft-profile-editor to:
-  create a new reference
- to update a reference that is not used by any instances
- update an author that is not referenced in an instance nor used by any names
FLOR-47
> Draft profile editor permissions for references

- app/controllers/profile_items_controller.rb
- app/controllers/profile_texts_controller.rb
- app/helpers/profile/profile_items_helper.rb
- app/models/profile/profile_item.rb
- app/views/instances/tabs/_tab_profile_v2.html.erb
- app/views/profile_items/_no_delete_reasons.html.erb
- app/views/profile_items/index.turbo_stream.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/profile/profile_item_spec.rb
- test/controllers/profile_items_controller_test.rb
- test/factories/profile_item.rb
- We don't show the delete button when the profile item is cited in other profile items
-  Fixed up the bug around profile text update. Couldn't update a profile text due to `value` field not set
Delete a profile item (for a draft instance) that is cited by another profile item
FLOR-51
> Don't show the delete button when a profile item is cited by another item

- app/controllers/profile_item_annotations_controller.rb
- app/views/profile_item_annotations/_form.html.erb
- app/views/profile_item_annotations/delete.turbo_stream.erb
- app/views/profile_items/index.turbo_stream.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/controllers/profile_item_annotations_controller_spec.rb
We are going to allow user to save a blank profile item annotation which will be considered by the system as a delete profile item annotation.
Add a profile item annotation, save, and then clear the field and save again.
FLOR-52
> Allow a user to remove a profile item annotation

- build_prod/config-prod.ed
- config/history/changes-2025.yml
- config/version.properties
- lib/tasks/build_prod.rake
Just leave production AR TZ as :utc
The config-prod.ed script is failing on teamcity with no clear message why.
The script simply changes the prod active_record TZ from :local to :utc.
I added this script when migrating from CSIRO to AWS - and the script was probably needed then during the transition from one environment to the other.
We now don't need the script and will just leave the AR default TZ as :utc.
Build change
Build change
Build on TC
> Build: Remove scripted changing of active_record timezome from :localhost to :utc

- app/controllers/instances_controller.rb
- app/models/instance.rb
- app/views/instances/tabs/_tab_copy_to_new_profile_v2.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/instance_spec.rb
Copy tab (with default reference) for standalone & non-draft instances
- Assign a draft-editor role to a user
- Select a standalone and non-draft instance. The copy tab will show up
FLOR-31
> Only show the copy tab to standalone & non-draft instance

- app/views/search/search_targets/_standard_targets.html.erb
- config/history/changes-2025.yml
- config/version.properties
Minor change to order of Search Targets
Drop down search target list
> NSL-5088: Loader Search Targets: change order of target options to reflect use

- app/models/concerns/author_validations.rb
- config/history/changes-2025.yml
- config/version.properties
- test/models/author/validations/length/abbrev_too_long_test.rb
- test/models/author/validations/length/full_name_too_long_test.rb
- test/models/author/validations/length/name_too_long_test.rb
- test/models/author/validations/length/notes_too_long_test.rb
Add length validations to Author model via a concern.
Enter over-length data in name, abbrev, full_name, and notes.
> NSL-5368: Author: Check field lengths before saving to database

- app/controllers/instances_controller.rb
- app/models/ability.rb
- app/views/instances/tabs/_all_tab_headings.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/ability_spec.rb
Adding permissions for draft-editor to access unpub tab for draft instances
FLOR-34
> Draft editor permission for unpub tab

- app/controllers/instances_controller.rb
- app/helpers/instances_helper.rb
- app/models/ability.rb
- app/models/instance.rb
- app/models/profile/profile_item.rb
- app/views/instances/_delete_widgets.html.erb
- app/views/instances/tabs/_all_tab_headings.html.erb
- app/views/instances/tabs/_tab_edit_profile_v2.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/ability_spec.rb
- spec/models/instance_spec.rb
- spec/models/profile/profile_item_spec.rb
- spec/views/instances/tabs/tab_edit_profile_v2_spec.rb
- spec/views/names/tabs/tab_instances_profile_v2_partial_spec.rb
- test/controllers/profile_items_controller_test.rb
- test/factories/language.rb
Draft editor permission for deleting a draft instance
FLOR-69
> Draft editor permission for deleting draft instance

- app/models/product.rb
- app/models/product/role.rb
- app/models/role.rb
- app/models/user.rb
- app/models/user/product_role.rb
- config/history/changes-2025.yml
- config/version.properties
- db/structure.sql
- spec/models/profile/profile_item/defined_query/product_and_product_item_configs_spec.rb
- spec/models/session_user_spec.rb
- spec/models/user_spec.rb
- spec/views/layouts/_user_menu_spec.rb
- test/factories/product_role.rb
- test/factories/user_product_role.rb
- test/fixtures/product_roles.yml
- test/fixtures/roles.yml
- test/fixtures/user_product_roles.yml
Re-arrange the associations between Users, Roles, and User_Product_Role.
Change to the database tables and then to the models for user roles.
All new role-based tasks.
> FLOR-72:  Foa Project permissions: add a Product_Role table

- app/models/instance.rb
- app/views/instances/widgets/_no_delete_reasons.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/author_spec.rb
- spec/models/instance/as_copier_spec.rb
- spec/models/instance_spec.rb
- test/factories/language.rb
Draft editor: Only offer the delete instance button if there are no profile items attached to the instance.
FLOR-69
> FLOR-69: Don't offer instance delete button if there are profile items

- app/models/ability.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/ability_spec.rb
Adding permissions for draft-editor to edit a relationship instance where the cited by is draft and is associated to a product that the user belongs to.
As draft editor, access the relationship instance, you should see an edit tab and be able to update the instance fields.
FLOR-70
> Draft editor permission for editing relationship instance

- app/models/concerns/author_validations.rb
- config/history/changes-2025.yml
- config/version.properties
- db/structure.sql
- test/models/author/validations/length/abbrev_too_long_test.rb
Set length validation to allow for 150 chars to match the DDL change.
Enter values into author abbreviation field.
> NSL-5386: Author abbreviation: Allow for up to 150 characters

- app/models/instance.rb
- app/models/instance/as_copier.rb
- app/views/instances/tabs/_tab_copy_to_new_profile_v2.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/instance/as_copier_spec.rb
Add ability for draft-editor to copy profile items for an instance by offering them an option to copy profile items
As draft-editor user, select a draft standalone instance  to copy, if there's a profile item attached to it, there should be an option to copy the profile items as well.
FLOR-53
> Add ability for draft-editor to copy profile items for an instance

- app/views/loader/batch/reviewers/tabs/_tab_details.html.erb
- config/history/changes-2025.yml
- config/version.properties
Allow for batch reviewers not linked to an organisation.
> NSL-5376: Show unaffiliated users in batch stack listing

- app/views/application/search_results/review/_loader_name_record.html.erb
- app/views/loader/names/tabs/forms/_form_for_heading.html.erb
- app/views/loader/names/tabs/heading_record_tabs/_tab_details.html.erb
- config/history/changes-2025.yml
- config/version.properties
Use remark_to_reviewer as an alternative to in-batch-notes on header records.
Log in as a batch owner, add remark_to_reviewer values to family header records, view on Details tab, and then login as a reviewer and see the display of query results.
> NSL-5193:  Loader Name: Allow header records to have a remark_to_reviewer value and display it

- app/models/instance/as_typeahead/for_product_item_config.rb
- app/views/profile_items/index.turbo_stream.erb
- app/views/profile_texts/create.turbo_stream.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/instance/as_typeahead/for_product_item_config_spec.rb
- Updated the link profile item's typeahead to be able to query by a name's full name.
- Fixed up the UI particularly on the link profile item checkbox to hide after creating a draft item.
FLOR-55
> FLOR-55 Update typeahead sql query

- app/models/instance/as_typeahead/for_product_item_config.rb
- config/version.properties
- spec/models/instance/as_typeahead/for_product_item_config_spec.rb
Improved link profile item typeahead query to include foreign characters
FLOR-55
> Use f_unaccent to query for foreign chars in typeahead

- app/controllers/instances_controller.rb
- app/models/search/on_instance/base.rb
- app/views/instances/tabs/_tab_show_1.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/controllers/instances_controller_spec.rb
Addressed issue with instance copying; ensure profile items are copied as well. And address some n+1 queries reported by bullet.
Select an instance with profile items to copy ->  tick the copy profile items checkbox -> copy
FLOR-53
> FLOR-53: Fixup copying of profile items of an instance

- app/views/loader/names/tabs/heading_record_tabs/_tab_details.html.erb
- config/history/changes-2025.yml
- config/version.properties
Small change on Details tab for heading records
Go to details tab for loader name heading records
> NSL-5406: Loader Name: Switch order of full and simple names on loader name details tab for heading records too

- app/views/application/search_results/review/_loader_name_record.html.erb
- config/history/changes-2025.yml
- config/version.properties
Small change to the way results are re-written to provide family headings.
Display loader names as a reviewer - with a synonym belonging to a different family than the accepted name.
> NSL-5428: Loader Name: Suppress display of dummy family headers for synonyms/misapplications

- app/models/instance/as_copier.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/instance/as_copier_spec.rb
Set the `tree_element_id` of copied profile item to nil to avoid db error around `profile_instance_constraint`
FLOR-53
> FLOR-53: Fix for copying profile item with tree_element_id

- app/models/concerns/reference_scopes.rb
- app/models/search/on_model/where_clauses.rb
- config/history/changes-2025.yml
- config/version.properties
- test/models/search/on_reference/citation/fragment_anomalies/prefix_fragment_search_test.rb
- test/models/search/on_reference/citation/hookers_apostrophe_test.rb
Improve Reference citation-text search
Ref searches documented in the Jira.
> NSL-5398:  Reference Search: Switch dictionary from 'english' to 'simple' and silently remove wildcards from user-supplied search terms

- app/controllers/profile_items/links_controller.rb
- app/models/profile/profile_text.rb
- app/services/profile_items/links/create_service.rb
- app/services/profile_items/links/update_service.rb
- app/views/profile_items/_delete_widgets.html.erb
- app/views/profile_items/_edit_widgets.html.erb
- app/views/profile_items/index.turbo_stream.erb
- app/views/profile_items/links/create.html.erb
- app/views/profile_items/links/update_failed.turbo_stream.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/controllers/profile_items/links_controller_spec.rb
- spec/services/profile_items/links/create_service_spec.rb
- spec/services/profile_items/links/update_service_spec.rb
Adding support for draft profile editors to edit a linked profile item
For a draft instance, select a linked profile item -> click on edit
FLOR-74
> Edit a linked profile item

- app/views/application/search_results/review/_loader_name_record.html.erb
- config/history/changes-2025.yml
- config/version.properties
Reviewer output of loader name records is a complex algorithm.
In that  output, we noticed that in-batch-notes were appearing before the previous record’s distribution entry.
That isn’t expected or desirable and this jira fixes that.
Output batch data for reviewers as discussed with Anna.
> NSL-5433: Loader: Make in-batch note appear below distribution entry of previous record

- app/models/profile/profile_item.rb
- app/models/profile/profile_item_reference.rb
- app/services/profile_items/links/update_service.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/profile/profile_item_spec.rb
- spec/services/profile_items/links/update_service_spec.rb
When converting a linked profile item to a `fact`, also copy the profile item references of the source if there are any.
FLOR-74
> Copy profile item reference of the sourced profile item

- app/models/search/loader/name/field_rule.rb
- config/history/changes-2025.yml
- config/version.properties
The SQL for the query was referring to users.name instead of users.user_name - so hadn't been changed to match a recent DDL improvement.
Run the search with that directive.
> Loader Review: Fix problem in has-review-comment-by: search directive

- app/models/instance/as_copier.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/instance/as_copier_spec.rb
Setup copied profile item's `published_date` to nil and set the `created_by` and `updated_by` to user currently doing the action
select an instance with profile item -> click on copy tab 
FLOR-53
> FLOR-53: Setup copied profile item's published_date to nil

- app/helpers/loader/names_helper.rb
- app/views/application/search_results/review/_loader_name_record.html.erb
- app/views/application/search_results/review/loader_name_record/_in_batch_note.html.erb
- app/views/application/search_results/review/loader_name_record/_ordinary_record.html.erb
- app/views/application/search_results/review/loader_name_record/_show_captured.html.erb
- app/views/application/search_results/review/loader_name_record/_show_family_and_not_flushing.html.erb
- app/views/application/search_results/review/loader_name_record/_white_space_row.html.erb
- app/views/application/search_results/review/loader_name_record/in_batch_note/_one_record.html.erb
- app/views/application/search_results/review/loader_name_record/ordinary_record/_one_record.html.erb
- app/views/application/search_results/review/loader_name_record/show_family_and_not_flushing/_family_formatted_text_above.html.erb
- app/views/application/search_results/review/loader_name_record/show_family_and_not_flushing/_family_of_review_result.html.erb
- app/views/application/search_results/review/loader_name_record/show_family_and_not_flushing/_higher_rank_comment.html.erb
- app/views/application/search_results/review/loader_name_record/show_family_and_not_flushing/_white_space_before_family.html.erb
- config/history/changes-2025.yml
- config/version.properties
Change the display of in-batch-note records so they show details and hence let reviewers add comments.  Re-factor the complex loader-name display code to make this change manageable.
Display a batch as a reviewer and query/display/comment on in-batch-notes.
> NSL-5435: Loader Review: Allow reviewer comments on in-batch-note

- app/models/loader/batch/review/period.rb
- config/brakeman.ignore
- config/history/changes-2025.yml
- config/version.properties
Also add brakeman ignores for false positives in this code.
The problem arises using UTC database date comparisons with Rails app local date - especially before 10am local time which is UTC midnight.
Run auto tests before 10am - and test whether a period set to start "today" is open before 10am local time.
> NSL-5442: Make batch review period date comparisons timezone neutral

- config/history/changes-2025.yml
Added a Jira number to change log/release notes.
Display release notes for 2025.
No need to bump version.
> Set NSL-5441 in release notes as the Jira for the revision of org-not-voted: made on 21 May

- app/controllers/search_controller.rb
- app/models/search/on_model/count_query.rb
- app/models/search/on_model/list_query.rb
- app/views/application/search_results/review/_loader_name_record.html.erb
- app/views/loader/names/tabs/in_batch_note_record_tabs/_tab_details.html.erb
- config/history/changes-2025.yml
- config/version.properties
Use session view_mode in loader_name query logic to filter out in-batch-compiler-notes from SQL query results if users is a reviewer.
Login as a reviewer and query a batch of loader_name records that has an in-batch-compiler-note - you should not see the record in any search results.
> NSL-5439: Loader Review: Make in-batch compiler notes invisible to reviewers

- app/models/name/as_typeahead/on_full_name.rb
- config/history/changes-2025.yml
- config/version.properties
- test/models/name/as_typeahead/on_full_name/should_include_names_without_instances_test.rb
Reverts NSL-945 that added this restriction to a typeahead query - we now simply remove that line of code.
Create name, grab a reference and add the new name to the reference within a New Instance - should now be possible.
> NSL-4889:  Reference New Instance: include names without an instance in the names typeahead

- app/views/application/search_results/review/_loader_name_record.html.erb
- config/history/changes-2025.yml
- config/version.properties
Displaying loader name records to reviewers in a way that emulates the old Word documents is pretty tricky and this fixes a small bug in the recent rewrite of that code.
See Jira.
> NSL-5450: Loader Review: Do not display heading record full names e.g for Family heading records

- app/views/application/search_results/review/_loader_name_record.html.erb
- config/history/changes-2025.yml
- config/version.properties
In-batch-notes weren't being displayed, which was a regression.  I've tweaked and improved the display algorithm to fix this.
Display batch records as a reviewer.
> NSL-5439: Loader Review: hide in-batch-compiler from reviewers - fix problem in re-factored display algorithm

- .nsl-test-configs/editor-config.rb
- app/javascript/prompt_form_save.js
- app/javascript/search_result_focus.js
- app/views/admin/_index.html.erb
- app/views/layouts/application.html.erb
- config/history/changes-2025.yml
- config/version.properties
Introduce a functionality to request saving unsaved form data, applicable across all forms, including those not defined by a specific class. This is behind a feature flag.
Enable the flag, go to a form and make changes, navigate away from the page and a popup will show up prompting you to save your changes.
FLOR-76
> Apply unsaved form prompt to all forms

- app/models/ability.rb
- app/models/profile/profile_item_annotation.rb
- app/services/profile_items/published/create_new_version_service.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/ability_spec.rb
- spec/services/profile_items/published/create_new_version_service_spec.rb
Adding a service responsible for creating a versioned copy of a profile item (copying the profile item and its associated annotations, profile text, and profile item references)
Backend change, can only be tested from the specs atm or via console
FLOR-77
> Create new version of Profile::ProfileItem Service

- app/models/loader/batch/review.rb
- app/models/loader/batch/review/period.rb
- app/views/loader/batch/review/periods/tabs/_tab_details.html.erb
- config/history/changes-2025.yml
- config/version.properties
Use the review period's active? method to correctly decided whether the comment form should be offered.
Comment on a loader name record on the same day the batch review period closes.
> NSL-5468: Batch Review: Keep commenting available until the end of the review period's closing day

- app/javascript/prompt_form_save.js
- app/javascript/search_result_focus.js
- config/history/changes-2025.yml
- config/version.properties
Fixup unstable/buggy prompt message for unsaved form
Edit a foa form from the editor -> navigate away by visiting other tabs, links, submitting search form -> a popup should show
FLOR-76
> FLOR-76 Refactor and fix prompt's unstable behaviour

- app/helpers/application_helper.rb
- app/helpers/tabs_helper.rb
- app/javascript/search_result_focus.js
- app/models/user.rb
- app/views/names/show.html.erb
- app/views/names/tabs/_tab.html.erb
- app/views/names/tabs/_tab_instances_profile_v2.html.erb
- app/views/names/tabs/_tabs.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/helpers/instances_helper_spec.rb
- spec/helpers/tabs_helper_spec.rb
- spec/models/user_spec.rb
Adding support for multi-product tabs based on the available user's product role. Behind a feature flag `multi_product_tabs_enabled`
Login with 2 or more user product role (with diff product) -> search for a name -> tabs will be available for each product
FLOR-82
> Multi-product support in tabs behind feature flag

- .nsl-test-configs/editor-config.rb
- app/controllers/instances_controller.rb
- app/models/profile/profile_item/defined_query/product_and_product_item_configs.rb
- app/models/user.rb
- app/views/instances/tabs/_all_multi_product_tab_headings.html.erb
- app/views/instances/tabs/_all_tab_headings.html.erb
- app/views/instances/tabs/_tab.html.erb
- app/views/instances/tabs/_tab_profile_v2.html.erb
- app/views/names/tabs/_tab.html.erb
- app/views/names/tabs/_tabs.html.erb
- app/views/names/tabs/_tabs_multi_product.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/profile/profile_item/defined_query/product_and_product_item_configs_spec.rb
- spec/models/user_spec.rb
- spec/views/instances/tabs/tabs_all_tab_headings_partial_spec.rb
- spec/views/names/tabs/tabs_partial_spec.rb
Muti-tabs for instances and cleanup codes.  The tabs for the names and instances are now supporting multipe products based on the user's product roles. The FOA/PRODUCT profile tab are now filtered and working for the specified product (ie adding item config, profile texts, etc).  
FLOR-82
FLOR-82
> Multi-tabs for instances page and refactor codes

- app/models/search/loader/name/field_rule.rb
- app/views/loader/names/help/_fields.html.erb
- config/history/changes-2025.yml
- config/version.properties
New query directive
As a batch loader run the query directive on a batch.
> NSL-5362:  Loader Batch Query: Add query syn-matched-to-autonym for preferred matches that are autonyms

- app/models/concerns/loader/name/sort_key.rb
- config/history/changes-2025.yml
- config/version.properties
Tweaking the sort-key algorithm.
As described in the Jira.
> NSL-5451: Loader Batch: Genus name now consistently sorting before first child species in batch

- app/controllers/search_controller.rb
- config/history/changes-2025.yml
- config/version.properties
Re-work the search controller changes so CSV output and print output still both work.
Get Instances as CSV and loader names in print output.
> NSL-5163:  CSV Output: link to CSV export of instance query results works again without breaking the print: directive

- app/helpers/tabs_helper.rb
- app/views/layouts/_new_multi_product_menu.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/helpers/tabs_helper_spec.rb
This pull request updates the logic for displaying menu items in the `app/views/layouts/_new_multi_product_menu.html.erb` file. The main change is that the "Names" submenu is now conditionally rendered based on the availability of the "new" tab, improving menu accuracy and reducing clutter.
> Don't render the New Name option in the menu to foa users

- app/views/names/tabs/_tab_more.html.erb
- app/views/names/tabs/_tabs_row_2.html.erb
- config/history/changes-2025.yml
- config/product_tabs/tabs.json
- config/version.properties
- spec/services/products/product_tab_config_spec.rb
This pull request adds a new tab called `more_refresh` to the name index view and ensures it is properly displayed in the UI when available. The changes update both the configuration and the view logic to support this new tab.
> Refresh tab access for product roles

- app/models/user.rb
- app/services/products/product_context_service.rb
- app/services/products/product_tab_service.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/user_spec.rb
- spec/services/products/product_context_service_spec.rb
- spec/services/products/product_tab_service_spec.rb
This pull request introduces consistent ordering of products by `context_sort_order` (and then by name) across several parts of the codebase, ensuring that products are presented in a predictable and logical order both in application logic and tests. It also adds and updates tests to verify the new ordering and context grouping behavior.
> Sort the product context in the menu using the product's context_sort_order

- app/models/ability.rb
- config/history/changes-2025.yml
- config/version.properties
- spec/models/ability_spec.rb
This pull request updates the logic for determining profile editing permissions to ensure that users can edit profile items and instances only if they are associated with the correct products.
> Refactor profile editor permissions

- app/services/products/product_context_service.rb
- app/views/instances/tabs/_all_tab_headings.html.erb
- app/views/instances/tabs/_tab_copy_to_new_profile_v2.html.erb
- config/history/changes-2025.yml
- config/version.properties
- spec/services/products/product_context_service_spec.rb
This pull request refactors how product references are accessed and displayed in the "Copy to New Profile" tab, shifting from user-based product lookups to context-based lookups. It introduces a new method to fetch products by context, updates view logic to use this method, and adds corresponding tests for improved reliability and maintainability.
FLOR-116
> FIxup foa copy tab not working anymore after implementing the product context

- app/views/loader/names/tabs/_tab_edit.html.erb
- app/views/loader/names/tabs/forms/_form_convert_misapp_to_syn.html.erb
- app/views/loader/names/tabs/forms/_form_convert_syn_to_misapp.html.erb
- app/views/loader/names/tabs/forms/_form_for_misapp.html.erb
- app/views/loader/names/tabs/forms/_form_for_synonym.html.erb
- config/history/changes-2025.yml
- config/version.properties
Forms to allow edit operations to change record_type from 'synonym' to 'misapp' and vice versa
Batch loader operation - described in the Jira.
> NSL-5590: Batch Loader: Allow conversion from synonym to misapplication and vice versa

- app/models/concerns/loader/name/voting.rb
- app/models/search/loader/name/field_rule.rb
- app/views/application/search_results/review/link_texts/_loader_name.html.erb
- app/views/loader/names/review/tabs/main/_tab_details.html.erb
- config/history/changes-2025.yml
- config/version.properties
Add some extra info on the loader name record display for reviewers.
Login in as a registered batch reviewer and query records, including some marked NFP.
> NSL-5591: Batch Review: Show NFP status of loader name records to batch reviewers
