app/views/loader/names/tabs/ref_instance/synonyms/_no_preferred_match.html.erb, config/history/changes-2024.yml, config/version.properties
Removed unneeded SQL query from synonym logic - no change to behaviour
=> NSL-4633:  Loader: Minor tweak to Ref Instance tab logic 

app/controllers/loader/batch/bulk_controller/remove_syn_conflicts_job.rb, app/models/loader/name/bulk_syn_conflicts_search.rb, app/models/loader/name/draft_taxonomy_remover.rb, app/models/loader/name/draft_taxonomy_remover/remover.rb, app/models/search/loader/name/field_rule.rb, app/models/tree_join_v.rb, app/views/loader/names/help/_fields.html.erb, config/history/changes-2024.yml, config/version.properties
- better log messages, 
- preflight check to avoid removing taxa with sub-taxa, 
- clearer query
- added 20s sleep between delete-syn-conflicts remove calls
=> NSL-5007: Loader: Improvements for syn-match-in-tree and delete-syn-conflicts

app/views/authors/_tab_show_1.html.erb, app/views/instances/tabs/_tab_show_1.html.erb, app/views/names/details/_meta.html.erb, app/views/references/tabs/_tab_show_1.html.erb, config/history/changes-2024.yml, config/version.properties
…thor, Instance, Name, and Reference.
=> NSL-4998: Source system meta data: Standardised the display across Author, Instance, Name, and Reference.

app/controllers/loader/name/matches_controller.rb, app/views/loader/name/matches/cancel_force_remove.js.erb, app/views/loader/name/matches/force_remove.js.erb, app/views/loader/name/matches/prepare_force_remove.js.erb, app/views/loader/names/tabs/_tab_matched_name.html.erb, app/views/loader/names/tabs/details/matches/_misapplied.html.erb, app/views/loader/names/tabs/details/matches/misapplieds/_one_misapplied.html.erb, app/views/loader/names/tabs/details/matches/misapplieds/one_misapplied/_possible_matches.html.erb, app/views/loader/names/tabs/matched_name/_force_remove.html.erb, config/history/changes-2024.yml, config/routes.rb, config/version.properties
Using this will allow delete of instances created via the loader
Also refactored some misapplied gui code.
=> NSL-5011:  Loader: Add Force Remove Match option on Matched Name tab.

app/controllers/names_controller.rb, config/history/changes-2024.yml, config/version.properties, test/fixtures/names.yml
Uncomment the full set of checks on name changes.
Adjust/correct fixture so failing test passes.
=> NSL-2494: Additional, part 2.

app/views/loader/names/tabs/forms/_form_for_accepted_or_excluded.html.erb, app/views/loader/names/tabs/forms/_form_for_misapp.html.erb, app/views/loader/names/tabs/forms/_form_for_synonym.html.erb, app/views/loader/names/tabs/forms/_name_status.html.erb, app/views/loader/names/tabs/forms/_simple_name_full_name.html.erb, config/history/changes-2024.yml, config/version.properties
Also made other minor adjustments on Loader Name forms
=> NSL-5114: Loader: Move Name Status field under Simple Name field

app/javascript/application.js, app/javascript/utilities/page_load_performance.js, app/views/layouts/_footer.html.erb, config/history/changes-2024.yml, config/importmap.rb, config/version.properties
Second attempt - re-write as a utility module.
=> NSL-5149:  Javascript: Fix minor intermittent JS error showing up in the JS console

app/controllers/loader/names_controller.rb, config/history/changes-2024.yml, config/version.properties
This was likely a side-effect of NSL-5056
=> NSL-5179: Loader: Fix problem creating loader-name synonym

app/controllers/passwords_controller.rb, app/models/ability.rb, app/views/passwords/password_changed.html.erb, app/views/passwords/show_password_form.html.erb, app/views/passwords/updated.html.erb, config/history/changes-2024.yml, config/routes.rb, config/version.properties
This seems to have stopped working when I upgraded the Rails 7.1 with more Turbo.
This is an urgent fix and is a bit rough around the edges, but has to go in pronto.
There were JavaScript errors showing up in the console and part of the fix was to replace rendering with redirects.
=> NSL-5191:  Change Password: working again

app/assets/stylesheets/components/batch-loader.css, app/models/concerns/loader/name/review_comments.rb, app/models/loader/name.rb, app/views/application/search_results/review/_loader_name_record.html.erb, app/views/application/search_results/review/_loader_name_stored_comment.html.erb, app/views/application/search_results/review/_loader_name_stored_distribution.html.erb, app/views/loader/names/review/tabs/common/_one_comment.html.erb, app/views/loader/names/review/tabs/common/_tab_rev_comments.html.erb, config/history/changes-2024.yml, config/version.properties
Also show only direct comments on the details tab.
Some code refactoring along the way: moved some code to a concern and replaced alias_attribute with alias_method.
=> Fix cumulative comment counts.

app/models/search/loader/name/field_rule.rb, app/views/loader/names/help/_review_fields.html.erb, config/history/changes-2024.yml, config/version.properties
Also updated the query help text for these fields.
=> NSL-5211: Loader Review: Flag has-review-comment: and no-distribution: search directives as taking no argument

app/models/ability.rb, config/history/changes-2024.yml, config/version.properties, test/controllers/instances/tabs/authorisation/for_foa/show_foa_tab_test.rb
Only users assigned to the foa group should have access to the foa editor
=> Update permissions for foa edit

.github/workflows/lint-ruby.yml, .github/workflows/test.yml, .nsl-test-configs/database.yml, .nsl-test-configs/editor-config.rb, app/controllers/concerns/search/query_defaults.rb, app/helpers/instances_helper.rb, app/views/application/search_results/review/_loader_name_record.html.erb, config/brakeman.ignore, config/version.properties
Adding a github workflow for automated tests
1. Added minitest workflow
2. Added brakeman workflow
3. Fixedup some of the brakeman failures and ignore some that we could not fix easily
=> Gh workflow tests

app/models/concerns/instance_treeable.rb, app/models/instance.rb, app/views/instances/_delete_widgets.html.erb, app/views/layouts/_menu_links.html.erb, config/history/changes-2024.yml, config/version.properties
Addresses problem in Algae which has 4 classification trees.
=> NSL-5242: Instance delete: Check for FK in all classifcation trees, not just in the accepted tree, before offering a delete button

app/models/loader/name/review/vote.rb, app/views/loader/name/review/votes/create.js.erb, app/views/loader/name/review/votes/destroy.js.erb, config/history/changes-2024.yml, config/version.properties
Also add valdation on uniqueness to back up database constraint.
=> NSL-5234: APC Workflow: Voting - reset the Vote tab after creating/removing a vote

app/controllers/loader/batches_controller.rb, app/models/concerns/loader/name/review_comments.rb, app/views/application/search_results/review/_loader_name_record.html.erb, app/views/application/search_results/review/_loader_name_stored_comment.html.erb, app/views/application/search_results/review/_loader_name_stored_distribution.html.erb, config/history/changes-2024.yml, config/version.properties, db/structure.sql, test/fixtures/loader/batch.yml, test/fixtures/loader/name.yml, test/models/search/loader/name/hybrid/no_hybrid_flag_test.rb, test/models/search/loader/name/simple_with_any_batch_test.rb, test/models/search/loader/name/simple_with_batch_name_asterisk_test.rb
Also add some early fixtures for loader batch and loader name.
=> NSL-5230: Loader: Re-work and correct comment counts for reviewers

app/controllers/profile_items_controller.rb, app/models/profile/profile_item/defined_query/product_and_product_item_configs.rb, config/history/changes-2024.yml, config/version.properties, test/fixtures/product_item_config.yml, test/fixtures/profile_item.yml, test/fixtures/profile_item_type.yml, test/models/profile/profile_item/defined_query/product_and_productt_item_configs_test.rb
Modify the product_item_config query to filter object type of text for now
=> Make sure to only return product_item_config of object type text for now

app/models/profile/product_item_config.rb, app/models/profile/profile_item.rb, app/models/profile/profile_item/defined_query/product_and_product_item_configs.rb, config/history/changes-2024.yml, config/version.properties, test/fixtures/product_item_config.yml, test/models/profile/product_item_config_test.rb, test/models/profile/profile_item_test.rb
Sorting the profile items based on its product_item_config's sort_order
[x] Bump version  4.1.5.12
[x] Update changelog
=> Default scope sort order for product item config

Dockerfile.dev, config/version.properties
Adding a bundle path environment after the latest gems upgrades
=> Add the bundle path environment in dockerfile

app/models/search/loader/name/field_rule.rb, app/views/application/search_results/_loader_name_record.html.erb, app/views/loader/names/help/_fields.html.erb, app/views/loader/names/help/_review_fields.html.erb, app/views/orgs/tabs/_tab_details.html.erb, config/history/changes-2024.yml, config/version.properties
To find loader name records with or without votes of any or a specific value, by organisation or for any organisation
=> NSL-5246: Batch Review voting: search directives for reviewers and compilers.

app/models/user.rb, app/views/instances/tabs/_tab_show_1.html.erb, config/history/changes-2024.yml, config/version.properties
Once merged and confirmed working, I will add in tests
=> Fixup template error for moss env

app/controllers/application_controller.rb, app/models/ability.rb, app/models/session_user.rb, config/history/changes-2025.yml, config/version.properties, spec/controllers/instances_controller_spec.rb, spec/models/ability_spec.rb, spec/models/profile/profile_item/defined_query/product_and_product_item_configs_spec.rb, spec/models/session_user_spec.rb, spec/services/users/profile_context_spec.rb, spec/services/users/profile_contexts/apni_spec.rb, spec/services/users/profile_contexts/base_spec.rb, spec/services/users/profile_contexts/foa_spec.rb, test/factories/user.rb, test/models/profile/profile_item/defined_query/product_and_productt_item_configs_test.rb, test/models/search/users.rb
A technical change that should have no affect on functions
=> NSL-5305:  Code infrastructure: Rename the User model to SessionUser

app/views/profile_item_references/_edit_form.html.erb, config/history/changes-2025.yml, config/version.properties
In the profile editor, display the profile item reference's citation
=> Use the reference citation when displaying reference in profile editor

app/views/instances/tabs/_tab_product_config_profile_item_form.html.erb, app/views/instances/tabs/_tab_profile_v2.html.erb, app/views/profile_item_references/_delete_widgets.html.erb, app/views/profile_item_references/_edit_form.html.erb, app/views/profile_items/_delete_widgets.html.erb, app/views/profile_items/destroy.turbo_stream.erb, app/views/profile_items/index.turbo_stream.erb, app/views/profile_texts/create.turbo_stream.erb, config/history/changes-2025.yml, config/version.properties
Fixup the overlapping texts between the profile item reference and the delete button, and some several spacings
=> Fixup some spacings in the foa editor

.github/PULL_REQUEST_TEMPLATE.md, config/version.properties
Just adding a PR template for github PRs. This will automatically populate the description of a PR once opened/created
=> Github Pr template

app/models/loader/name/make_one_instance/make_one_synonymy_instance.rb, config/history/changes-2025.yml, config/version.properties
Minor fix - remove stray char
Run batch load in test that hit the initial problem
=> NSL-5341:  Loader: Fix typo from yesterday

db/structure.sql
Programmer use only - a modified version of structure.sql.
rake test ....
Not bumping version or adding to release notes.
=> Modified structure.sql

Gemfile, Gemfile.lock, app/assets/stylesheets/layouts/layout-2021.css, app/models/user.rb, app/views/layouts/_user_menu.html.erb, config/history/changes-2025.yml, config/version.properties, spec/rails_helper.rb, spec/views/layouts/_user_menu_spec.rb, test/factories/user_product_role.rb, test/fixtures/users.yml
Product role list in the menu
FLOR-42
=> Product role in the menu 

app/models/session_user.rb, app/models/user.rb, config/history/changes-2025.yml, config/version.properties, spec/models/session_user_spec.rb, spec/models/user_spec.rb
Adding a way to identify a user role via a method.
=> User object and role method

app/views/loader/names/review/tabs/main/_tab_vote.html.erb, app/views/loader/names/review/tabs/main/votes/votable/voting_in_progress/_can_vote.html.erb, app/views/loader/names/review/tabs/main/votes/votable/voting_in_progress/can_vote/_heading.html.erb, app/views/loader/names/review/tabs/main/votes/votable/voting_in_progress/can_vote/heading/vote/_form.html.erb, config/history/changes-2025.yml, config/version.properties
Several tweaks to the Reviewers' Vote tab - remove some stray stuff then tighten up the display
Anna will review against Jira.
=> NSL-5330: Loader Batch Review Voting: Tidy up the Reviewers Vote tab

app/controllers/instances_controller.rb, app/helpers/application_helper.rb, app/models/ability.rb, app/models/user.rb, app/views/instances/tabs/_all_tab_headings.html.erb, app/views/instances/tabs/_tab_copy_to_new_profile_v2.html.erb, config/history/changes-2025.yml, config/version.properties, spec/models/ability_spec.rb
Adding permissions for draft-editor role
- Assign a draft-editor role to a user
- Select a draft instance
=> Add a copy instance permission for draft-editor role

config/history/changes-2025.yml
Tiny change to release note Jira number.
Read Release Notes.
Didn't change these.
=> NSL-5146: Correct release note that was referring to NSL-5164

app/models/profile/product.rb, app/models/profile/product_item_config.rb, app/models/profile/profile_item.rb, app/models/profile/profile_item_annotation.rb, app/models/profile/profile_item_reference.rb, app/models/profile/profile_item_type.rb, app/models/profile/profile_object_type.rb, app/models/profile/profile_text.rb, app/models/role.rb, app/models/session_user.rb, app/models/user.rb, app/models/user/product_role.rb, app/views/layouts/_user_menu.html.erb, config/history/changes-2025.yml, config/version.properties, db/structure.sql, spec/models/profile/profile_item/defined_query/product_and_product_item_configs_spec.rb, spec/models/session_user_spec.rb, spec/models/user_spec.rb, spec/views/layouts/_user_menu_spec.rb, test/factories/role.rb, test/factories/user_product_role.rb, test/fixtures/roles.yml, test/fixtures/user_product_roles.yml
A DB structure change for a recently-created table.
Test user product role related functions
=> FLOR-56: Foa Project: Rename table product_role_type to role

app/models/ability.rb, app/views/instances/tabs/_all_tab_headings.html.erb, app/views/names/tabs/_tab_instances_profile_v2.html.erb, app/views/names/tabs/_tabs.html.erb, config/history/changes-2025.yml, config/version.properties, spec/views/names/tabs/tab_instances_profile_v2_partial_spec.rb, spec/views/names/tabs/tabs_partial_spec.rb
Adding draft-editor permissions for new instance via names
FLOR-41
=> Draft editor permissions for new instance via name

app/models/ability.rb, app/views/instances/tabs/_all_tab_headings.html.erb, app/views/instances/tabs/_tab_edit.html.erb, config/history/changes-2025.yml, config/version.properties, spec/models/ability_spec.rb, spec/views/instances/tabs/tabs_all_tab_headings_partial_spec.rb
Adding a draft-editor permission for updating or deleting a draft instance associated to their product
=> Draft editor permissions for editing/deleting draft instance

app/views/admin/_index.html.erb, config/history/changes-2025.yml, config/version.properties
Minor change to add one extra line of info on Admin Configuration page
Go to Admin -> Configuration, look for Schema search path in Database config area
=> NSL-5397: Admin configuration page: display schema search path

app/controllers/loader/names_controller.rb, app/helpers/loader/names_helper.rb, app/views/application/search_results/review/_loader_name_record.html.erb, app/views/loader/names/tabs/details/_core_data.html.erb, app/views/loader/names/tabs/forms/_form_for_accepted_or_excluded.html.erb, app/views/loader/names/tabs/forms/_form_for_heading.html.erb, app/views/loader/names/tabs/heading_record_tabs/_tab_details.html.erb, config/history/changes-2025.yml, config/version.properties
Two new columns/fields for presenting information to batch reviewers.
As a batch loader Editor add sample data to these fields for header records and accepted/excluded records then query the records as a batch reviewer.
=> NSL-5193:  Loader Name: Add formatted_text_above and formatted_text_below fields

app/assets/stylesheets/utilities/colors.css, app/views/application/search_results/review/_loader_name_record.html.erb, app/views/loader/names/tabs/in_batch_note_record_tabs/_tab_details.html.erb, config/history/changes-2025.yml, config/version.properties
Adjustment of batch review outputs for in-batch-note records
Create an in-batch-note record for a batch and add formatted reference list, then execute a wildcard search on the batch as a reviewer.
=> NSL-5193:  Loader Name: Adjust in-batch-note.notes review display to suit reference lists

app/assets/stylesheets/print.css, app/models/search/loader/name/field_rule.rb, app/models/search/loader/name/rewrite_results_showing_extras.rb, app/models/search/parsed_request.rb, app/views/application/search_results/print/records/loader/_name.html.erb, app/views/application/search_results/print/records/loader/name/record_types/_accepted.html.erb, app/views/application/search_results/print/records/loader/name/record_types/_formatted_text_above.html.erb, app/views/application/search_results/print/records/loader/name/record_types/_formatted_text_below.html.erb, app/views/loader/names/help/_fields.html.erb, app/views/loader/names/help/_review_fields.html.erb, app/views/loader/names/review/tabs/common/_one_comment.html.erb, config/history/changes-2025.yml, config/version.properties, db/structure.sql
Also introduce print-with-comments review directive and in-batch-note directive.
Changes to print-ready output to keep up with recent developments.
Log in as batch reviewer and use print: directive.
=> NSL-5193:  Loader Name: Adjust print-ready output for reviewers to show formatted notes and text

app/views/loader/names/tabs/details/_core_data.html.erb, config/history/changes-2025.yml, config/version.properties
Trivial change to swap vertical position of two fields
Show Loader Name Details tab
=> NSL-5406: Loader Name: Switch order of full and simple names on loader name details tab

app/models/search/loader/name/field_rule.rb, config/history/changes-2025.yml, config/version.properties
Modify some loader name query SQL
Run loader name vote queries mentioned in the Jira.
=> NSL-5395: Loader Name: Show real family headers in vote query results

app/models/search/loader/name/field_rule.rb, config/history/changes-2025.yml, config/version.properties
Change to SQL for some queries.
Run the org-voted:, org-not-voted: org-voted-yes:, org-voted-no: queries
=> NSL-5394: Loader Name: Show full context in vote query results

app/views/application/search_results/review/_loader_name_record.html.erb, config/history/changes-2025.yml, config/version.properties
Small change to view logic for loader name records
Run loader name org-voted: queries.
=> NSL-5428: Loader Name: Tweak the suppression of family headings to make sure real headings are shown

app/models/search/loader/name/field_rule.rb, app/views/loader/names/help/_review_fields.html.erb, config/history/changes-2025.yml, config/version.properties
SQL needs to correctly grab relevant headings and synonymy for this query.
Set up and query complex patterns of organisation voting.
=> NSL-5395: Loader Review: Revise and improve SQL for org-not-voted: directive

app/models/user.rb, app/views/loader/names/review/tabs/main/details/periods/_comment.html.erb, config/history/changes-2025.yml, config/version.properties, test/controllers/session/actions/new_session_unknown_user_creates_user_record_test.rb, users
Remove some metadata boilerplate from comment tab; when user first logs in, give their users record better audit details.
Look at comments tab; login as a first time user and look at subsequent Users record 
- [ x] Bumped version
- [ x] Updated changelog (Please add an entry to the changelog for the current year)
=> Loader: Minor changes

app/views/application/search_results/review/_loader_name_record.html.erb, config/history/changes-2025.yml, config/version.properties
Query batches as a reviewer - look at records with formatted text above and formatted text below values.
=> NSL-5432: Loader: Remove stray ">" in review output for some note and text fields

app/controllers/loader/name/review/comments_controller.rb, app/views/loader/name/review/comments/_form.html.erb, config/history/changes-2025.yml, config/version.properties
=> NSL-5431:  Loader: Users no longer enter a comment type to make a review comment

app/views/application/search_results/review/_loader_name_record.html.erb, config/history/changes-2025.yml, config/version.properties
Fixing a typo that was causing the bug.  
Test case is in the Jira.
=> NSL-5440: Loader Review: Fix comment/distribution wrongly appearing under an excluded name

app/models/search/loader/name/field_rule.rb, config/history/changes-2025.yml, config/version.properties
Change logic to get correct results for this directive.
Queries of various cases or organisations having voted or not voted on records - including cases where other orgs have voted on the target loader name records.  The cases here are very complex and difficult to itemise.
=> Loader Review: Revise org-not-voted: search directive SQL

app/models/ability.rb, app/models/profile/profile_item.rb, app/models/user.rb, app/views/instances/tabs/_tab_copy_to_new_profile_v2.html.erb, app/views/instances/tabs/_tab_product_config_profile_item_form.html.erb, app/views/profile_items/_edit_tab_profile_item.html.erb, app/views/profile_items/_linked_profile_item.html.erb, config/history/changes-2025.yml, spec/models/ability_spec.rb, spec/models/profile/profile_item_spec.rb
- Profile editor permissions for editing/deleting profile items
- Refactored the view templates with partials
FLOR-75
=> FLOR-75 - Profile editor permissions for published profile items

app/views/application/search_results/review/_loader_name_record.html.erb, config/history/changes-2025.yml, config/version.properties
Problem was introduced under nsl-5435 re-factoring.
Use "show context" link from details tab as an example.
=> Loader Reveiew: Show first accepted/excluded name in output.

config/history/changes-2025.yml
Read release note
NO - no need
=> NSL-5448: Fix type in release note

.nsl-test-configs/editor-config.rb, app/javascript/application.js, app/javascript/prompt_form_save.js, app/javascript/search_result_focus.js, app/views/admin/_index.html.erb, app/views/layouts/_unsaved_changes_modal.html.erb, app/views/layouts/application.html.erb, app/views/profile_item_annotations/_form.html.erb, app/views/profile_item_references/_edit_form.html.erb, app/views/profile_item_references/_form.html.erb, app/views/profile_items/_product_item_config_dropdown.html.erb, app/views/profile_items/destroy.turbo_stream.erb, app/views/profile_texts/_form.html.erb, app/views/profile_texts/create.turbo_stream.erb, config/history/changes-2025.yml, config/importmap.rb, config/version.properties
When a user has unsaved changes in the profile item form, prompt them to save or cancel (lose the changes)
Go to a profile item -> edit fields -> click on a tab
FLOR-76
=> FLOR-76 - Prompt for unsaved profile item form changes

app/views/loader/batch/reviews/tabs/_tab_reviewers.html.erb, config/history/changes-2025.yml, config/version.properties
Remove boiler plate text, also fix error in previous change's release note.
View list of reviewers as batch loader - look at one reviewer entry who has made a comment.
=> NSL-5457: Batch Loader: remove boiler plate text "need a way to see the comments"

app/views/application/search_results/_loader_name_record.html.erb, config/history/changes-2025.yml, config/version.properties
See Jira - navigate reference records with console open, watch for errors.
=> NSL-5502: JavaScript: Remove rogue script tag showing up as a console error

app/models/search/bulk_processing_log/field_rule.rb, config/history/changes-2025.yml, config/version.properties
Enable batches, select a batch, go to batch tab, follow link to view recent logs.
=> NSL-5530: Loader logs: Allow search directive 'latest:' to be submitted without an argument

config/history/changes-2025.yml
Add slash to code end tag.
Load 2025 change history page.
thinking for this minor tweak we won't bump version and the change log update is just the added slash
=> NSL-5527: fix code tag pair in history entry

config/history/changes-2025.yml
Just updating the change log to point to correct JIRA
=> Update change log to point to FLOR-111

app/assets/stylesheets/print.css, app/views/application/search_results/print/records/loader/name/record_types/_accepted.html.erb, app/views/application/search_results/print/records/loader/name/record_types/_excluded.html.erb, config/history/changes-2025.yml, config/version.properties
Show votes on print output
Query loader names as a batch reviewer and use the print: directive.
=> NSL-5393:  Batch Review Print: Show votes on print output

app/services/products/product_tab_service.rb, config/history/changes-2025.yml, config/version.properties, spec/services/products/product_tab_service_spec.rb
This pull request improves the robustness of the `ProductTabService` by adding error handling for database permission errors and ensures this behavior is properly tested. The main changes include catching a specific database exception and logging it, as well as adding a corresponding test case.
=> Handle permission errors in products_for_context

app/models/concerns/loader/name/review_comments.rb, app/views/application/search_results/review/loader_name_record/show_family_and_not_flushing/_family_of_review_result.html.erb, app/views/loader/name/review/comments/_form.html.erb, config/history/changes-2025.yml, config/version.properties
Show comments on family header on screen and in print view
See details in Jira
=> NSL-5571: Batch Review: 

app/models/loader/name.rb, app/models/search/loader/name/field_rule.rb, app/views/application/search_results/link_texts/loader/_name.html.erb, app/views/application/search_results/print/records/loader/name/record_types/_synonym.html.erb, app/views/application/search_results/print/records/loader/name/record_types/misapplied/_construct_entry.html.erb, app/views/application/search_results/review/link_texts/_loader_name.html.erb, app/views/loader/names/review/tabs/main/_tab_details.html.erb, config/history/changes-2025.yml, config/version.properties
Details in the Jira
Details in the Jira
=> NSL-5588:  Batch Load and Review: Show misapp and pro parte data on web and print outputs consistently

app/views/instances/tabs/batch_loader/_form_for_accepted_excluded.html.erb, app/views/instances/tabs/batch_loader/_form_to_supplement_concept.html.erb, config/history/changes-2025.yml, config/version.properties
Allow choice of batch on Loader 2 tab
See Jira - use the Instance Loader 2 tab - try different batches.
=>  NSL-5581: Batch Loading: Allow user to choose batch on Instance Loader 2 tab

app/controllers/loader/names_controller.rb, app/models/concerns/loader/name/flipped_synonym.rb, app/views/instances/tabs/batch_loader/_form_to_supplement_concept.html.erb, config/history/changes-2025.yml, config/version.properties
=> NSL-5198: Batch Loading: Set and use synonym type on Instance Loader 2 tab
